// Import mongoose
const mongoose = require('mongoose');

// Contract schema
const contractSchema = new mongoose.Schema(
  {
    // Original name of the uploaded file (e.g., "john_contract.pdf")
    originalFileName: {
      type: String,
      required: true,
    },

    // The path where the file is saved 
    filePath: {
      type: String,
      required: true,
    },

    // What type of file was uploaded? "pdf" or "image"
    fileType: {
      type: String,
      enum: ['pdf', 'image'],
      required: true,
    },

    // Document Status Update
    status: {
      type: String,
      enum: [
        'uploaded',       // just uploaded, nothing done yet
        'ocr_processing', // OCR agent is reading the text
        'ocr_done',       // OCR finished
        'classifying',    // classification agent is working
        'classified',     // classification done
        'extracting',     // extraction agent is working
        'extracted',      // extraction done
        'summarizing',    // summarization agent is working
        'completed',      // all agents done
        'failed',         // something went wrong
      ],
      default: 'uploaded',
    },

    // The raw text extracted by the OCR agent
    extractedText: {
      type: String,
      default: '', 
    },

    // What type of contract is this? (set by classification agent)
    // e.g., "employment_contract", "nda", "freelance_agreement"
    documentType: {
      type: String,
      default: '',
    },

    // Key information pulled out by the extraction agent
    extractedInfo: {
      employeeName: { type: String, default: '' },
      salary: { type: String, default: '' },
      startDate: { type: String, default: '' },
      endDate: { type: String, default: '' },
      jobTitle: { type: String, default: '' },
      companyName: { type: String, default: '' },
    },

    // A summary generated by the summarization agent
    summary: {
      type: String,
      default: '',
    },

    // Validation / signature step
    validationStatus: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
    },

    // Notes written by the HR person during validation
    validationNotes: {
      type: String,
      default: '',
    },

    // Error messages if something went wrong during processing
    errorMessage: {
      type: String,
      default: '',
    },
  },
  {
    // Add createdAt and updatedAt timestamps
    timestamps: true,
  }
);

// model
const Contract = mongoose.model('Contract', contractSchema);

module.exports = Contract;